os: linux
dist: xenial
language: node_js
node_js: '12'

cache: yarn

install:
  - yarn install

script:
  - yarn webpack --mode production

deploy:
  edge: true # Use dpl v2 - https://docs.travis-ci.com/user/deployment-v2
  provider: pages
  strategy: git
  keep_history: false
  commit_message: Deploy %{git_tag} @ %{git_sha}
  local_dir: ./dist
  on:
    tags: yes # Not `true` so `branch` is considered too
    branch: master
