dist: xenial
language: node_js
node_js: '11'

cache: yarn

install:
  - yarn install

script:
  - yarn build --no-progress

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: ./dist
  on:
    branch: master
